import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { KengineRum } from '@khulnasoft/react-rum'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const apiKey = process.env.NEXT_PUBLIC_KENGINE_KEY;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KengineRum apiKey={apiKey as string} enableWebVitals  fallback={<>Its broken</>}>
          {children}
        </KengineRum>
      </body>
    </html>
  )
}
